# Generated by Django 2.2.28 on 2023-03-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form5500',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sponsor_Name', models.CharField(max_length=255, verbose_name='Sponsor_Name')),
                ('Sponsor_Street', models.CharField(max_length=100, verbose_name='Sponsor_Street')),
                ('Sponsor_City', models.CharField(max_length=100, verbose_name='Sponsor_City')),
                ('Sponsor_State', models.CharField(max_length=2, verbose_name='Sponsor_State')),
                ('Sponsor_Zipcode', models.CharField(max_length=5, verbose_name='Sponsor_Zipcode')),
                ('EIN', models.CharField(max_length=20, verbose_name='EIN')),
                ('Participants', models.IntegerField(verbose_name='Participants')),
                ('Plan_Asset', models.BigIntegerField(verbose_name='Plan_Asset')),
                ('Broker_Name', models.CharField(max_length=255, verbose_name='Broker_Name')),
                ('Provider_Name', models.CharField(max_length=255, verbose_name='Provider_Name')),
                ('Industry_Description', models.CharField(max_length=100, verbose_name='Industry_Description')),
            ],
        ),
    ]
